site_name: Machine Learning
pages:
- [index.md, Home]
- [install.md, 'General', 'Installation']
- [data/preprocessing.md, 'Data', 'Pre-processing']
- [approaches/approaches.md, 'Learning approaches', 'Approaches']
- [approaches/clustering.md, 'Learning approaches', 'Clustering']
- [approaches/supervised.md, 'Learning approaches', 'Supervised']
theme: readthedocs
site_author: ""
repo_url: https://github.com/willembressers/machinelearning
include_search: true
