site_name: Machine Learning
pages:
- [index.md, Home]
- [install.md, Installation]
- [data/preprocessing.md, 'Data', 'Pre-processing']
- [approaches/clustering.md, 'Learning approaches', 'Clustering']
theme: readthedocs
site_author: ""
repo_url: https://github.com/willembressers/machinelearning
include_search: true
